TASK-56314 : Illustration: webnotification of call recording (#127)
exo-addons/web-conferencing pull request #132
Opened 2022-04-22 09:18 UTC by IlhemEssaadi

ISSUES : When we hover on the avatar of the notification recording of a room call, it displays the room ID instead of the room name.
FIX : the problem is that the room ID is displayed instead of the room name and it is fixed by getting the name of the chat room from callInfo.

2022-04-22 09:45 UTC, boubaker approved these changes

2022-04-25 08:49 UTC, boubaker approved these changes

2022-04-25 08:49 UTC, boubaker approved these changes, later dismissed

2022-04-25 09:14 UTC, boubaker requested changes
the code source is empty after rebase, isn't it. What happened ?

2022-04-25 09:32 UTC, hbenali commented
> the code source is empty after rebase, isn't it. What happened ?

Already made by https://github.com/exoplatform/web-conferencing/commit/42cca47cf5917059aeda7e83ba687cc70bf55125#diff-494e6de84b769510574f567989ea374cb5bb522a4016c81728fef678c9bdfbc8R94 We could close this PR.

2022-04-25 10:10 UTC, boubaker commented
> > the code source is empty after rebase, isn't it. What happened ?
> 
> Already made by [42cca47#diff-494e6de84b769510574f567989ea374cb5bb522a4016c81728fef678c9bdfbc8R94](https://github.com/exoplatform/web-conferencing/commit/42cca47cf5917059aeda7e83ba687cc70bf55125#diff-494e6de84b769510574f567989ea374cb5bb522a4016c81728fef678c9bdfbc8R94) We could close this PR.

ok, thanks @hbenali . @IlhemEssaadi can you please lose this PR

2022-04-25 11:38 UTC, closed without merging