fix: Agenda : if external visio have a long url, unable to store the event
exo-addons/web-conferencing pull request #310
Opened 2024-06-06 07:58 UTC by rdenarie

Before this fix, if the visio url is longer than 500 char, and when it is used for a space event, the visio link was not savec because the filed in db is limited to 500chars This commit add a check when filling the space meeting url, to not add a link longer than 500 chars

2024-06-07 10:39 UTC, ahamdi requested changes

2024-06-07 10:39 UTC, ahamdi commented on webapp/src/main/webapp/vue-apps/SpaceAdministrationVisioConference/components/VideoConferenceLinkDrawer.vue
> +      console.log('validForm', this.isValidForm);
IMO this is not needed

2024-06-07 12:02 UTC, rdenarie commented on webapp/src/main/webapp/vue-apps/SpaceAdministrationVisioConference/components/VideoConferenceLinkDrawer.vue
> +      console.log('validForm', this.isValidForm);
updated

2024-06-10 12:27 UTC, rdenarie commented
@mkrout @azayati @ahamdi up to review, thanks

2024-06-10 12:28 UTC, azayati approved these changes
LGTM

2024-06-10 12:41 UTC, rdenarie commented
cc @ahamdi as you made a change request, I need your validation to merge

2024-06-11 17:08 UTC, ahamdi approved these changes

2024-06-11 17:08 UTC, merged