TASK-46211 : fixed meeting recording being saved in last participating user recording folder
exo-addons/web-conferencing pull request #58
Opened 2021-08-23 15:56 UTC by nidhalnidhal

Before this fix , the recording of a meeting is always saved in the recording folder related to the last participating user in the call , so i fixed this by altering the condition that determines where the recording has to be saved so that it takes in charge the "space-event" meeting type.

2021-08-24 07:29 UTC, rdenarie requested changes
The task reference in the title is not the good one. Can you update ?
Thanks

2021-08-24 11:53 UTC, rdenarie requested changes
Can you update the commit message to target the correct task ? in addition can you put the PR description (Why and how) in the commit message ?
Thanks

2021-08-24 11:53 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/WebConferencingService.java
> +        if (!uploadInfo.getType().equals(OWNER_TYPE_SPACEEVENT) && !uploadInfo.getIdentity().equals(uploadingUser)) {
Can uploadInfo.getType() be equals to OWNER_TYPE_SPACE ? What we do in this can ?

2021-08-26 16:22 UTC, nidhalnidhal commented on services/src/main/java/org/exoplatform/webconferencing/WebConferencingService.java
> +        if (!uploadInfo.getType().equals(OWNER_TYPE_SPACEEVENT) && !uploadInfo.getIdentity().equals(uploadingUser)) {
in this case , we  also save the recording in the space's recording folder. I updated the code.

2021-08-27 06:58 UTC, rdenarie approved these changes

2021-08-27 08:07 UTC, merged