MAINT-51942: Clean up jitsi started group calls on server startup
exo-addons/web-conferencing pull request #82
Opened 2021-12-07 12:18 UTC by hakermi

**ISSUE**: Some launched group  calls stays on join state for unexpected reasons which leads to a wrong information for the user
**FIX**: Do a clean up of jitsi started group calls

2021-12-07 16:15 UTC, rdenarie commented
@hakermi can you ping me to review the PR ?
As it seems a complex fix, it could be usefull to make pair review, so that you can explain to me your choices

2021-12-08 09:54 UTC, rdenarie requested changes

2021-12-08 09:54 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/WebConferencingService.java
> +      user = organization.getUserHandler().findUserByName(id, UserStatus.ENABLED);
Keep any

2021-12-08 09:54 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/WebConferencingService.java
> +      if (!savedCalls.isEmpty()) {
not needed

2021-12-08 10:26 UTC, hakermi commented on services/src/main/java/org/exoplatform/webconferencing/WebConferencingService.java
> +      user = organization.getUserHandler().findUserByName(id, UserStatus.ENABLED);
done

2021-12-08 10:26 UTC, hakermi commented on services/src/main/java/org/exoplatform/webconferencing/WebConferencingService.java
> +      if (!savedCalls.isEmpty()) {
removed

2021-12-08 11:03 UTC, rdenarie approved these changes

2021-12-08 11:03 UTC, merged