Task 53432: Add Analytics metric for recordings in jitsi.
exo-addons/web-conferencing pull request #96
Opened 2022-02-09 09:52 UTC by Montassar-Hamadi

Improvement: add two metrics of recorded calls (Recorded file size, uploading status) to module analytics. So in this implementation, I fired two events of the same type EVENT_CALL_RECORDED in success and failed cases of uploading of the recorded file, then I added the necessary instructions to process the data sent to the listener and add these two parameters in the recorded call case.

2022-02-09 11:35 UTC, hbenali commented
Please rebase your branch and remote [SWF commit](https://github.com/exoplatform/web-conferencing/pull/96/commits/4c1848d7fcccb0e60236186ee8cc991d6f6a1e22)

2022-02-09 16:27 UTC, rdenarie requested changes

2022-02-09 16:27 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/listener/analytics/WebConferencingListener.java
> +      statisticData.setStatus(info.get("upload_status").equals(WebConferencingService.STATUS_OK) ? StatisticData.StatisticStatus.OK : StatisticData.StatisticStatus.KO);
```suggestion
```

Please use statisticData.setStatus, and do it outside of the if

2022-02-11 08:19 UTC, rdenarie requested changes
Please check your PR, there is a lot of tags related to git merge.

2022-02-11 08:19 UTC, rdenarie commented on .vscode/settings.json
> +{
Remove this file

2022-02-11 08:19 UTC, rdenarie commented on pom.xml
> +<<<<<<< HEAD
remove this

2022-02-14 08:50 UTC, rdenarie requested changes
Where did you add the i18n key for recordedFileSizeInMB ?

2022-02-14 08:50 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/WebConferencingService.java
> +                + resource.getStatus());
can you remove the added spaces ?

2022-02-14 08:50 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/WebConferencingService.java
> +      if(eventName.equals(EVENT_CALL_RECORDED) && fileSize != null) {
```suggestion
      if(fileSize != null) {
```

2022-02-14 08:50 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/listener/analytics/WebConferencingListener.java
> +    if(statisticData.getOperation().equals("callRecorded") && info.containsKey("file_size")) {
```suggestion
    if(info.containsKey("file_size")) {
```

2022-02-14 08:50 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/listener/analytics/WebConferencingListener.java
> +      statisticData.addParameter("recordedFileSize", info.get("file_size"));
```suggestion
      statisticData.addParameter("recordedFileSizeInMB", info.get("file_size"));
```

2022-02-14 10:22 UTC, Montassar-Hamadi commented
> Where did you add the i18n key for recordedFileSizeInMB ?

https://github.com/Meeds-io/analytics/pull/5

2022-02-14 10:42 UTC, rdenarie commented
:+1:

2022-02-21 13:24 UTC, rdenarie approved these changes

2022-02-21 14:49 UTC, merged